
version: '3.8'

services:
  customer-service:
    build: ./customer-service
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=insurance
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  policy-service:
    build: ./policy-service
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=insurance
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  claim-service:
    build: ./claim-service
    ports:
      - "8003:8003"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=claimsdb
    depends_on:
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "8004:8004"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=insurance
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  notification-service:
    build: ./notification-service
    ports:
      - "8005:8005"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  fraud-detection-service:
    build: ./fraud-detection-service
    ports:
      - "8006:8006"

  document-service:
    build: ./document-service
    ports:
      - "8007:8007"
    volumes:
      - ./storage:/data

  agent-management-service:
    build: ./agent-management-service
    ports:
      - "8008:8008"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=insurance
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  customer-ui:
    build: ./customer-ui
    ports:
      - "3000:3000"

  admin-ui:
    build: ./admin-ui
    ports:
      - "8081:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: insurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  pgdata:
