
version: '3.8'
services:
  db:
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
