# Build stage
FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
COPY client ./client
COPY index.html ./
COPY vite.config.js ./

RUN npm install
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]